//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZAProxy {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ZAProxy.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result from the server was empty..
        /// </summary>
        internal static string EmptyServerResult {
            get {
                return ResourceManager.GetString("EmptyServerResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CallAction received a failed result..
        /// </summary>
        internal static string FailedCallActionResult {
            get {
                return ResourceManager.GetString("FailedCallActionResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CallApi received a failed result..
        /// </summary>
        internal static string FailedCallApiResult {
            get {
                return ResourceManager.GetString("FailedCallApiResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This class does not support the supplied AuthenticationCredential..
        /// </summary>
        internal static string InvalidAuthenticationCredentialSupplied {
            get {
                return ResourceManager.GetString("InvalidAuthenticationCredentialSupplied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This class does not support the supplied AuthenticationMethod..
        /// </summary>
        internal static string InvalidAuthenticationMethodSupplied {
            get {
                return ResourceManager.GetString("InvalidAuthenticationMethodSupplied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The supplied string is not a well-formed query string..
        /// </summary>
        internal static string InvalidQueryString {
            get {
                return ResourceManager.GetString("InvalidQueryString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This class does not support the supplied SessionManagementMethod..
        /// </summary>
        internal static string InvalidSessionManagementMethodSupplied {
            get {
                return ResourceManager.GetString("InvalidSessionManagementMethodSupplied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CallAction received an unknown result..
        /// </summary>
        internal static string UnknownCallActionResult {
            get {
                return ResourceManager.GetString("UnknownCallActionResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CallView received an unkown result..
        /// </summary>
        internal static string UnknownCallViewResult {
            get {
                return ResourceManager.GetString("UnknownCallViewResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SetProxy received an unknown result..
        /// </summary>
        internal static string UnknownSetProxyResult {
            get {
                return ResourceManager.GetString("UnknownSetProxyResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requested component type is not registered..
        /// </summary>
        internal static string UnregisteredComponentRequested {
            get {
                return ResourceManager.GetString("UnregisteredComponentRequested", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server returned an authentication detection method that this client does not support..
        /// </summary>
        internal static string UnsupportedAuthorizationDetectionMethod {
            get {
                return ResourceManager.GetString("UnsupportedAuthorizationDetectionMethod", resourceCulture);
            }
        }
    }
}
