//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZAProxy {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ZAProxy.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CallAction received a failed result..
        /// </summary>
        internal static string CallActionFailedResult {
            get {
                return ResourceManager.GetString("CallActionFailedResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CallAction received an unknown result..
        /// </summary>
        internal static string CallActionUnknownResult {
            get {
                return ResourceManager.GetString("CallActionUnknownResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CallApi received a failed result..
        /// </summary>
        internal static string CallApiFailedResult {
            get {
                return ResourceManager.GetString("CallApiFailedResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CallView received an unkown result..
        /// </summary>
        internal static string CallViewUnknownResult {
            get {
                return ResourceManager.GetString("CallViewUnknownResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requested component type is not registered..
        /// </summary>
        internal static string ComponentNotRegistered {
            get {
                return ResourceManager.GetString("ComponentNotRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result from the server was empty..
        /// </summary>
        internal static string ResultFromServerWasEmpty {
            get {
                return ResourceManager.GetString("ResultFromServerWasEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SetProxy received an unknown result..
        /// </summary>
        internal static string SetProxyUnknownResult {
            get {
                return ResourceManager.GetString("SetProxyUnknownResult", resourceCulture);
            }
        }
    }
}
