using System.Collections.Generic;

namespace ZAProxy.Schema
{
    /// <summary>
    /// Describes a passive scanner.
    /// </summary>
    public class PassiveScanner
    {
        /// <summary>
        /// Gets or sets the threshold of alerts generated by the scanner.
        /// </summary>
        public AlertThreshold AlertThreshold { get; set; }

        /// <summary>
        /// Gets or sets the name.
        /// </summary>
        public string Name { get; set; }

        /// <summary>
        /// Gets or sets the ID.
        /// </summary>
        public int Id { get; set; }

        /// <summary>
        /// Gets or sets whether the scanner is enabled.
        /// </summary>
        public bool Enabled { get; set; }
    }
}
