using System.Collections.Generic;

namespace ZAProxy.Schema
{
    /// <summary>
    /// Describes a scanner.
    /// </summary>
    public class Scanner
    {
        /// <summary>
        /// Gets or sets whether all required dependencies in ZAP for this scanner are available.
        /// </summary>
        public bool AllDependenciesAvailable { get; set; }

        /// <summary>
        /// Gets or sets the policy ID.
        /// </summary>
        public int PolicyId { get; set; }

        /// <summary>
        /// Gets or sets the Common Weakness Enumeration ID this scanner searches for. See <see href="https://cwe.mitre.org/"/>.
        /// </summary>
        public int CweId { get; set; }

        /// <summary>
        /// Gets or sets the strength of attacks performed by the scanner.
        /// </summary>
        public AttackStrength AttackStrength { get; set; }

        /// <summary>
        /// Gets or sets the threshold of alerts generated by the scanner.
        /// </summary>
        public AlertThreshold AlertThreshold { get; set; }

        /// <summary>
        /// Gets or sets the name.
        /// </summary>
        public string Name { get; set; }

        /// <summary>
        /// Gets or sets the Web Application Security Consortium ID this scanner searches for. See <see href="http://www.webappsec.org/"/>.
        /// </summary>
        public int WascId { get; set; }

        /// <summary>
        /// Gets or sets the ID.
        /// </summary>
        public int Id { get; set; }

        /// <summary>
        /// Gets or sets whether the scanner is enabled.
        /// </summary>
        public bool Enabled { get; set; }

        /// <summary>
        /// Gets a list of scanner IDs on which this scanner is dependent.
        /// </summary>
        public IEnumerable<int> Dependencies { get; set; }
    }
}
